/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
  ],
  theme: {
    extend: {
      fontFamily: {
        'cormorant-infant': ['Cormorant Infant', 'serif'],
        'rouge-script': ['Rouge Script', 'cursive'],
        'optima-label-label-s': ['Optima', 'sans-serif'],
        'cormorant': ['Cormorant', 'serif'],
        'cormorant-garamond': ['Cormorant Garamond', 'serif'],
        'marck-script': ['Marck Script', 'cursive'],
      },
      fontSize: {
        '5xl': 'var(--font-size-5xl)',
        '29xl': 'var(--font-size-29xl)',
        'optima-label-label-s': 'var(--optima-label-label-s-size)',
        '13xl': 'var(--font-size-13xl)',
        'xs': 'var(--font-size-xs)',
      },
      colors: {
        burlywood: '#c79d70',
        peru: '#bb8554',
        seashell: 'rgba(255, 245, 235, 0.2)',
        navajowhite: '#ffcf9c',
        peachpuff: '#edccae',
        lightgray: '#dbcdbf',
        salmon: '#fd856c',
      },
      spacing: {
        '29xl': 'var(--gap-29xl)',
        '5xl': 'var(--gap-5xl)',
        'xs': 'var(--gap-xs)',
        '0': 'var(--gap-0)',
        'base': 'var(--gap-base)',
        '5xs': 'var(--gap-5xs)',
      },
      padding: {
        'base': 'var(--padding-base)',
        '29xl': 'var(--padding-29xl)',
        '5xs': 'var(--padding-5xs)',
        '61xl': 'var(--padding-61xl)',
        '5xl': 'var(--padding-5xl)',
        '12xs': 'var(--padding-12xs)',
        '11xs': 'var(--padding-11xs)',
        '21xl': 'var(--padding-21xl)',
        '3xs': 'var(--padding-3xs)',
        '6xs': 'var(--padding-6xs)',
        '33xl': 'var(--padding-33xl)',
        '7xs': 'var(--padding-7xs)',
        'lg': 'var(--padding-lg)',
        'sm': 'var(--padding-sm)',
      },
      borderRadius: {
        '21xl': 'var(--br-21xl)',
        '81xl': 'var(--br-81xl)',
        '13xl': 'var(--br-13xl)',
        '61xl': 'var(--br-61xl)',
        '29xl': 'var(--br-29xl)',
        '5xl': 'var(--br-5xl)',
        'xl': 'var(--br-xl)',
        'base': 'var(--br-base)',
        '5xs': 'var(--br-5xs)',
        '221xl': 'var(--br-221xl)',
      },
    },
  },
  plugins: [],
}